In [13]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt\
# some basic libraries required to do multivariate regression

In [14]:
df=pd.read_csv('data.csv')
df
#importing the sample data from a csv file 

instant  season  yr  mnth  holiday  weekday  workingday  weathersit  \
0         1       1   0     1        0        6           0           2   
1         2       1   0     1        0        0           0           2   
2         3       1   0     1        0        1           1           1   
3         4       1   0     1        0        2           1           1   
4         5       1   0     1        0        3           1           1   
5         6       1   0     1        0        4           1           1   
6         7       1   0     1        0        5           1           2   
7         8       1   0     1        0        6           0           2   
8         9       1   0     1        0        0           0           1   
9        10       1   0     1        0        1           1           1   
10       11       1   0     1        0        2           1           2   
11       12       1   0     1        0        3           1           1   
12       13       1   0     1        0        4           1           1   
13       14       1   0     1        0        5           1           1   
14       15       1   0     1        0        6           0           2   
15       16       1   0     1        0        0           0           1   
16       17       1   0     1        1        1           0           2   
17       18       1   0     1        0        2           1           2   
18       19       1   0     1        0        3           1           2   
19       20       1   0     1        0        4           1           2   
20       21       1   0     1        0        5           1           1   
21       22       1   0     1        0        6           0           1   
22       23       1   0     1        0        0           0           1   
23       24       1   0     1        0        1           1           1   
24       25       1   0     1        0        2           1           2   
25       26       1   0     1        0        3           1           3   
26       27       1   0     1        0        4           1           1   
27       28       1   0     1        0        5           1           2   
28       29       1   0     1        0        6           0           1   
29       30       1   0     1        0        0           0           1   
30       31       1   0     1        0        1           1           2   
31       32       1   0     2        0        2           1           2   
32       33       1   0     2        0        3           1           2   
33       34       1   0     2        0        4           1           1   
34       35       1   0     2        0        5           1           2   
35       36       1   0     2        0        6           0           2   
36       37       1   0     2        0        0           0           1   
37       38       1   0     2        0        1           1           1   
38       39       1   0     2        0        2           1           1   
39       40       1   0     2        0        3           1           2   
40       41       1   0     2        0        4           1           1   
41       42       1   0     2        0        5           1           1   
42       43       1   0     2        0        6           0           1   
43       44       1   0     2        0        0           0           1   
44       45       1   0     2        0        1           1           1   
45       46       1   0     2        0        2           1           1   
46       47       1   0     2        0        3           1           1   
47       48       1   0     2        0        4           1           1   
48       49       1   0     2        0        5           1           1   
49       50       1   0     2        0        6           0           1   

        temp     atemp       hum  windspeed  casual  registered   cnt  
0   0.344167  0.363625  0.805833   0.160446     331         654   985  
1   0.363478  0.353739  0.696087  

In [21]:
# y = m1*weekday + m2*workingday + m3*weathersit + c
reg = linear_model.LinearRegression()
# weekday , workingday , weathersit are independent variable . cnt is a dependent variable 
reg.fit(df[['weekday','workingday','weathersit']],df.cnt)
# training of model complete

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
reg.coef_
# will give three values of m1 , m2 , m3 respectively

array([  28.19252967,  398.73548566, -276.38595686])

In [18]:
reg.intercept_
# will give the value of c i.e. intercept

1450.1910685772134

In [19]:
reg.predict([[2,1,1]])

array([1628.92565671])

In [20]:
reg.predict([[2,0,1]])

array([1230.19017105])

In [22]:
((28.19252967)*2) + ((-276.38595686)*1) + 1450.1910685772134
#checking the result

1230.1901710572133